name: Deploy Web Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: CLIENT_DEPLOY

    steps:
    - name: node checkout
      uses: actions/checkout@v3

    - name: get nodejs
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: npm install
      run: npm install

    - name: npm run build
      run: npm run build

    - name: s3 upload
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }} 
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        aws s3 sync dist/ s3://$S3_BUCKET_NAME --acl private --delete --region $AWS_REGION
    
    - name: CloudFront invalidate
      uses: chetan/invalidate-cloudfront-action@master
      env:
        PATHS: '/*'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'
        DISTRIBUTION: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}